name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]

  # Permite rodar o workflow manualmente se você quiser forçar o deploy
  workflow_dispatch:

# Permissões do GitHub para publicar em Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy ativo por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build do site Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/setup-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deploy do site nas GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
